
name: python_test
version: 0.0.1
language: python
description: Run test use `make test`
public: true
tags:
  - python
  - test
inputs:
  - name: FLOW_ENABLE_FAILURE
    editable: true
    options:
      - TRUE
      - FALSE
outputs:
script_path: ./run.sh  
  
template: |  
  
  